// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcjoycwafpgyzddagmnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjam95Y3dhZnBneXpkZGFnbW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTM4MTYsImV4cCI6MjA2OTU2OTgxNn0.B2TCqUqUjo3rgH3L0Ye83Xmnmeckh6ISK4YIXAKsc6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});